### PR TITLE
Comment energy system network

### PR DESCRIPTION
**Pull request by TheOneAndra**
an exmple to help the reader/user understand the documentation better

**Changes proposed in this pull request**:
- Comment energy system network

The following steps were realized, as well (if applies):
- [ ] Update the CHANGELOG.md

### CODE REVIEW

**Comment by TheOneAndra** [comment]
@Bachibouzouk 
I would really avoid putting diminutivs in the RDT as they are more confusing to me than anything else (and I know what we are talking about, it might not be the case for the user). Moreover, it is clear the energy system network speaks about energy systems. So I think we should avoid diminutivs and repetitions such as "es_bus_list" and for example we could say "Bus list".

**Comment by Bachibouzouk** [comment]
"Bus list" cannot be a variable name in python, "es_bus_list" yes. Maybe I can just add this info as comment in the RTD as the RTD is ultimately intended for non-programmers. Btw it was not a diminutive but a unique name which refers unambiguously to this and only this attribute. If, in the future, for any reason, we have another bus list which is not the energy system's bus list, to refer to either one unambigously, one would need to use "the bus list from the energy network view-component", which is definitively much longer to say or write than "es_bus_list".

**Comment by TheOneAndra** [comment]
Ok I see now why you named them like that. But since we describe the interface in the RTD, should't we be as close as possible to the actual interface? It seems to me that a button in the tool will not be named "add_es_bus" (maybe that is up to debate?).
If we agree that buttons and texts in the tool should be easy to read and straight forward we could, for example, specify the unique id:
```
**button** :guilabel:`&Add a bus` 

*Unique id `add_es_bus`*
```
grafik

or more as comment for the devs ?
```
**button** :guilabel:`&Add a bus` 

.. Unique id `add_es_bus`
```

**Comment by Bachibouzouk** [comment]
I would say, either we insert it in the properties of the attribute (like in template view component) or we have it as a comment

**Comment by TheOneAndra** [comment]
It could be usefull to have it in the RTD if we want to keep the log always on screen. But if we follow the "easy to read" guideline, I would put it as comment then.

**Comment by Bachibouzouk** [comment]
I will make the change

**Review by Bachibouzouk — APPROVED** [review]

**Comment by TheOneAndra** [comment]
I notice all _Properties_ don't have the same highlights:
grafik

One solution would be to leave a blank line after the **Bold title** so that all properties are highlighted in blue and all section titles are **bold** like:
grafik

And **Button**

**Pull request merged**
