### PR TITLE
Populate views

### LINKED ISSUE #92: [Bug] View-comp doesn't appear in the RTD
Describe_the_bug
- Changes made in #82 don't appear in the RTD

### PR DESCRIPTION
**Pull request by Bachibouzouk**
**Changes proposed in this pull request**:
- Create endpoints and improve basic structure of interface

The following steps were realized, as well (if applies):
- [x] Apply black (`black . --exclude docs/`)
- [x] Update the CHANGELOG.md

The following optional steps were realized:
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: explain in readthedocs
- [ ] Write test(s) for your new patch of code

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl
-institut/open_plan/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
@mahendrark, you can take example on the first two commits to create the urls and html pages needed by the links I created in the 3rd commit.

**Comment by mahendrark** [comment]
@Bachibouzouk 

- I am not sure about the need for load project parameters and load scenario parameters VCs .They are just text fields, file input fields and buttons. We already have the project parameters and scenario parameters view-components which will list what are the respective parameters. 

- I did some thinking and I feel like we need to rethink the steps on the progression bar.  Some of them are redundant and/or unnecessary. - For eg.: Why cant we just include system setup (where I assume we populate the energy system with generation components, energy buses, etc.) and constraints together? That would be more logical given that the user accomplishes the task of setting up the energy system completely in one step. 

- I propose renaming 'Inputs' to 'Scenario Inputs'. On the view that comes up when the user clicks on Scenario Inputs, we will have fields for various Scenario Inputs and user provides the inputs here. 

- For working with Scenarios, we stick to what we have agreed on already. There is gonna be a separate menu on the menu tab using which the user can load scenario, create scenario, delete scenario, and alternate the project between different scenarios. The state of the entire progression bar changes when the user clicks on a specific scenario, thus updating all the inputs and settings and results, if available, to the current selected scenario. 

- Irrespective of the end result of the discussion in issue #26, I will assume that one project = one location for now. That means the energy systems in all of the scenarios are confined to the location of the project, for now. This is because I want to create the widget of the map with location in the view of the step 'Project Setup'. 

- You proposed that we drop 'Project Setup' from the progression bar as it typically will remain constant for all the scenarios. I agree with this idea.

**Comment by mahendrark** [comment]
I did some thinking and I feel like we need to rethink the steps on the progression bar.  Some of them are redundant and/or unnecessary. 
For eg.: Why cant we just include system setup (where I assume we populate the energy system with generation components, energy buses, etc.) and constraints together? That would be more logical given that the user accomplishes the task of setting up the energy system completely in one step.

**Comment by mahendrark** [comment]
@Bachibouzouk 

Can we merge this PR and start a fresh one? 
two many commits already and also too many lines of code

**Comment by Bachibouzouk** [comment]
@mahendrark - I will make some changes and merge, thanks for your changes :)

**Comment by Bachibouzouk** [comment]
@mahendrark - I made some modifications, could you make sure all links have an endpoint (create it if it does not exist) so that whenever someone clicks on a link they don't land on a "page does not exist".

**Pull request merged**
