### PR TITLE
Review input and output tables

### LINKED ISSUE #101: The output parameter installed power capacity must be redefined
We have to make two different outputs with two different units:
installed power [kW]
installed capacity [kWh]

### PR DESCRIPTION
**Pull request by TheOneAndra**
fix #101 

**Changes proposed in this pull request**:
- Update input table
- Update output table

The following steps were realized, as well (if applies):
- [x] Update the CHANGELOG.md

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl
-institut/open_plan/blob/dev/CONTRIBUTING.md).*<sub>

### CODE REVIEW

**Comment by TheOneAndra** [comment]
Check the **parameters** section of the RTD form this branch to see the latest updates
(For that go the end of this PR, under checks --> details)

**Review by mahendrark — APPROVED** [review]

**Comment by TheOneAndra** [comment]
This PR is left open for now because there is still work to do on these inputs and ouptus table. Still need to be discussed in a bigger working group.

**Comment by TheOneAndra** [comment]
It seems liek the `default `column for the outputs does not make much sense since output depend on the optimization.

For the inputs:
`2,Source power mix,Percentage of each source of power` How is the user suppose to know this as this seems like a result from the optimization (shouldn't this be an output?)
`23,Existing grid structure` &` 24,Future grid structure` They seem more adapted for the V2.0 of the tool.

Any thoughts @Bachibouzouk

**Comment by Bachibouzouk** [comment]
> `2,Source power mix,Percentage of each source of power` How is the user suppose to know this as this seems like a result from the optimization (shouldn't this be an output?)

This can be set as a goal --> as input

**Comment by Bachibouzouk** [comment]
> `23,Existing grid structure` &` 24,Future grid structure` They seem more adapted for the V2.0 of the tool.

Correct, I will work on the input files soon, I need a blocker of a few hours for that

**Review by Bachibouzouk — APPROVED** [review]
I added the columns Type, internal_categorization and tooltip for later use.
When internal_categorization is set to hidden, the parameter will not be displayed on RTD (not yet implemented

**Pull request merged**
